name = "cf-wbrtc-auth"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GOOGLE_CLIENT_ID = ""

# Create KV namespace: wrangler kv:namespace create KV
# Then update the id below
[[kv_namespaces]]
binding = "KV"
id = "badebab972474c26ae711fbc2b10d735"

[[durable_objects.bindings]]
name = "SIGNALING_DO"
class_name = "SignalingDO"

[[migrations]]
tag = "v1"
new_classes = ["SignalingDO"]

# Secrets (set via wrangler secret put):
# - GOOGLE_CLIENT_SECRET
# - JWT_SECRET
