name = "cf-wbrtc-auth"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GOOGLE_CLIENT_ID = "747065218280-ugkrbgaoik32f5mmi94sso4b0026j3cp.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "KV"
id = "badebab972474c26ae711fbc2b10d735"

[[durable_objects.bindings]]
name = "SIGNALING_DO"
class_name = "SignalingDO"

[[migrations]]
tag = "v1"
new_classes = ["SignalingDO"]
